library slownie.test;

import 'package:test/test.dart';

import 'package:slownie/slownie.dart';

main() {
  group('jeden do dziesięć tysięcy ', () {

    test('do tysiąca', () {
      expect(slownie("1"), "jeden");
      expect(slownie("2"), "dwa");
      expect(slownie("3"), "trzy");
      expect(slownie("4"), "cztery");
      expect(slownie("5"), "pięć");
      expect(slownie("6"), "sześć");
      expect(slownie("7"), "siedem");
      expect(slownie("8"), "osiem");
      expect(slownie("9"), "dziewięć");
      
      expect(slownie("10"), "dziesięć");
      expect(slownie("11"), "jedenaście");
      expect(slownie("12"), "dwanaście");
      expect(slownie("13"), "trzynaście");
      expect(slownie("14"), "czternaście");
      expect(slownie("15"), "piętnaście");
      expect(slownie("16"), "szesnaście");
      expect(slownie("17"), "siedemnaście");
      expect(slownie("18"), "osiemnaście");
      expect(slownie("19"), "dziewiętnaście");
      expect(slownie("20"), "dwadzieścia");
      expect(slownie("21"), "dwadzieścia jeden");
      expect(slownie("22"), "dwadzieścia dwa");
      expect(slownie("23"), "dwadzieścia trzy");
      expect(slownie("24"), "dwadzieścia cztery");
      expect(slownie("25"), "dwadzieścia pięć");
      expect(slownie("26"), "dwadzieścia sześć");
      expect(slownie("27"), "dwadzieścia siedem");
      expect(slownie("28"), "dwadzieścia osiem");
      expect(slownie("29"), "dwadzieścia dziewięć");
      expect(slownie("30"), "trzydzieści");
      expect(slownie("31"), "trzydzieści jeden");
      expect(slownie("32"), "trzydzieści dwa");
      expect(slownie("33"), "trzydzieści trzy");
      expect(slownie("34"), "trzydzieści cztery");
      expect(slownie("35"), "trzydzieści pięć");
      expect(slownie("36"), "trzydzieści sześć");
      expect(slownie("37"), "trzydzieści siedem");
      expect(slownie("38"), "trzydzieści osiem");
      expect(slownie("39"), "trzydzieści dziewięć");
      expect(slownie("40"), "czterdzieści");
      expect(slownie("41"), "czterdzieści jeden");
      expect(slownie("42"), "czterdzieści dwa");
      expect(slownie("43"), "czterdzieści trzy");
      expect(slownie("44"), "czterdzieści cztery");
      expect(slownie("45"), "czterdzieści pięć");
      expect(slownie("46"), "czterdzieści sześć");
      expect(slownie("47"), "czterdzieści siedem");
      expect(slownie("48"), "czterdzieści osiem");
      expect(slownie("49"), "czterdzieści dziewięć");
      expect(slownie("50"), "pięćdziesiąt");
      expect(slownie("51"), "pięćdziesiąt jeden");
      expect(slownie("52"), "pięćdziesiąt dwa");
      expect(slownie("53"), "pięćdziesiąt trzy");
      expect(slownie("54"), "pięćdziesiąt cztery");
      expect(slownie("55"), "pięćdziesiąt pięć");
      expect(slownie("56"), "pięćdziesiąt sześć");
      expect(slownie("57"), "pięćdziesiąt siedem");
      expect(slownie("58"), "pięćdziesiąt osiem");
      expect(slownie("59"), "pięćdziesiąt dziewięć");
      expect(slownie("60"), "sześćdziesiąt");
      expect(slownie("61"), "sześćdziesiąt jeden");
      expect(slownie("62"), "sześćdziesiąt dwa");
      expect(slownie("63"), "sześćdziesiąt trzy");
      expect(slownie("64"), "sześćdziesiąt cztery");
      expect(slownie("65"), "sześćdziesiąt pięć");
      expect(slownie("66"), "sześćdziesiąt sześć");
      expect(slownie("67"), "sześćdziesiąt siedem");
      expect(slownie("68"), "sześćdziesiąt osiem");
      expect(slownie("69"), "sześćdziesiąt dziewięć");
      expect(slownie("70"), "siedemdziesiąt");
      expect(slownie("71"), "siedemdziesiąt jeden");
      expect(slownie("72"), "siedemdziesiąt dwa");
      expect(slownie("73"), "siedemdziesiąt trzy");
      expect(slownie("74"), "siedemdziesiąt cztery");
      expect(slownie("75"), "siedemdziesiąt pięć");
      expect(slownie("76"), "siedemdziesiąt sześć");
      expect(slownie("77"), "siedemdziesiąt siedem");
      expect(slownie("78"), "siedemdziesiąt osiem");
      expect(slownie("79"), "siedemdziesiąt dziewięć");
      expect(slownie("80"), "osiemdziesiąt");
      expect(slownie("81"), "osiemdziesiąt jeden");
      expect(slownie("82"), "osiemdziesiąt dwa");
      expect(slownie("83"), "osiemdziesiąt trzy");
      expect(slownie("84"), "osiemdziesiąt cztery");
      expect(slownie("85"), "osiemdziesiąt pięć");
      expect(slownie("86"), "osiemdziesiąt sześć");
      expect(slownie("87"), "osiemdziesiąt siedem");
      expect(slownie("88"), "osiemdziesiąt osiem");
      expect(slownie("89"), "osiemdziesiąt dziewięć");
      expect(slownie("90"), "dziewięćdziesiąt");
      expect(slownie("91"), "dziewięćdziesiąt jeden");
      expect(slownie("92"), "dziewięćdziesiąt dwa");
      expect(slownie("93"), "dziewięćdziesiąt trzy");
      expect(slownie("94"), "dziewięćdziesiąt cztery");
      expect(slownie("95"), "dziewięćdziesiąt pięć");
      expect(slownie("96"), "dziewięćdziesiąt sześć");
      expect(slownie("97"), "dziewięćdziesiąt siedem");
      expect(slownie("98"), "dziewięćdziesiąt osiem");
      expect(slownie("99"), "dziewięćdziesiąt dziewięć");
      expect(slownie("100"), "sto");
      expect(slownie("101"), "sto jeden");
      expect(slownie("102"), "sto dwa");
      expect(slownie("103"), "sto trzy");
      expect(slownie("104"), "sto cztery");
      expect(slownie("105"), "sto pięć");
      expect(slownie("106"), "sto sześć");
      expect(slownie("107"), "sto siedem");
      expect(slownie("108"), "sto osiem");
      expect(slownie("109"), "sto dziewięć");
      expect(slownie("110"), "sto dziesięć");
      expect(slownie("111"), "sto jedenaście");
      expect(slownie("112"), "sto dwanaście");
      expect(slownie("113"), "sto trzynaście");
      expect(slownie("114"), "sto czternaście");
      expect(slownie("115"), "sto piętnaście");
      expect(slownie("116"), "sto szesnaście");
      expect(slownie("117"), "sto siedemnaście");
      expect(slownie("118"), "sto osiemnaście");
      expect(slownie("119"), "sto dziewiętnaście");
      expect(slownie("120"), "sto dwadzieścia");
      expect(slownie("121"), "sto dwadzieścia jeden");
      expect(slownie("122"), "sto dwadzieścia dwa");
      expect(slownie("123"), "sto dwadzieścia trzy");
      expect(slownie("124"), "sto dwadzieścia cztery");
      expect(slownie("125"), "sto dwadzieścia pięć");
      expect(slownie("126"), "sto dwadzieścia sześć");
      expect(slownie("127"), "sto dwadzieścia siedem");
      expect(slownie("128"), "sto dwadzieścia osiem");
      expect(slownie("129"), "sto dwadzieścia dziewięć");
      expect(slownie("130"), "sto trzydzieści");
      expect(slownie("131"), "sto trzydzieści jeden");
      expect(slownie("132"), "sto trzydzieści dwa");
      expect(slownie("133"), "sto trzydzieści trzy");
      expect(slownie("134"), "sto trzydzieści cztery");
      expect(slownie("135"), "sto trzydzieści pięć");
      expect(slownie("136"), "sto trzydzieści sześć");
      expect(slownie("137"), "sto trzydzieści siedem");
      expect(slownie("138"), "sto trzydzieści osiem");
      expect(slownie("139"), "sto trzydzieści dziewięć");
      expect(slownie("140"), "sto czterdzieści");
      expect(slownie("141"), "sto czterdzieści jeden");
      expect(slownie("142"), "sto czterdzieści dwa");
      expect(slownie("143"), "sto czterdzieści trzy");
      expect(slownie("144"), "sto czterdzieści cztery");
      expect(slownie("145"), "sto czterdzieści pięć");
      expect(slownie("146"), "sto czterdzieści sześć");
      expect(slownie("147"), "sto czterdzieści siedem");
      expect(slownie("148"), "sto czterdzieści osiem");
      expect(slownie("149"), "sto czterdzieści dziewięć");
      expect(slownie("150"), "sto pięćdziesiąt");
      expect(slownie("151"), "sto pięćdziesiąt jeden");
      expect(slownie("152"), "sto pięćdziesiąt dwa");
      expect(slownie("153"), "sto pięćdziesiąt trzy");
      expect(slownie("154"), "sto pięćdziesiąt cztery");
      expect(slownie("155"), "sto pięćdziesiąt pięć");
      expect(slownie("156"), "sto pięćdziesiąt sześć");
      expect(slownie("157"), "sto pięćdziesiąt siedem");
      expect(slownie("158"), "sto pięćdziesiąt osiem");
      expect(slownie("159"), "sto pięćdziesiąt dziewięć");
      expect(slownie("160"), "sto sześćdziesiąt");
      expect(slownie("161"), "sto sześćdziesiąt jeden");
      expect(slownie("162"), "sto sześćdziesiąt dwa");
      expect(slownie("163"), "sto sześćdziesiąt trzy");
      expect(slownie("164"), "sto sześćdziesiąt cztery");
      expect(slownie("165"), "sto sześćdziesiąt pięć");
      expect(slownie("166"), "sto sześćdziesiąt sześć");
      expect(slownie("167"), "sto sześćdziesiąt siedem");
      expect(slownie("168"), "sto sześćdziesiąt osiem");
      expect(slownie("169"), "sto sześćdziesiąt dziewięć");
      expect(slownie("170"), "sto siedemdziesiąt");
      expect(slownie("171"), "sto siedemdziesiąt jeden");
      expect(slownie("172"), "sto siedemdziesiąt dwa");
      expect(slownie("173"), "sto siedemdziesiąt trzy");
      expect(slownie("174"), "sto siedemdziesiąt cztery");
      expect(slownie("175"), "sto siedemdziesiąt pięć");
      expect(slownie("176"), "sto siedemdziesiąt sześć");
      expect(slownie("177"), "sto siedemdziesiąt siedem");
      expect(slownie("178"), "sto siedemdziesiąt osiem");
      expect(slownie("179"), "sto siedemdziesiąt dziewięć");
      expect(slownie("180"), "sto osiemdziesiąt");
      expect(slownie("181"), "sto osiemdziesiąt jeden");
      expect(slownie("182"), "sto osiemdziesiąt dwa");
      expect(slownie("183"), "sto osiemdziesiąt trzy");
      expect(slownie("184"), "sto osiemdziesiąt cztery");
      expect(slownie("185"), "sto osiemdziesiąt pięć");
      expect(slownie("186"), "sto osiemdziesiąt sześć");
      expect(slownie("187"), "sto osiemdziesiąt siedem");
      expect(slownie("188"), "sto osiemdziesiąt osiem");
      expect(slownie("189"), "sto osiemdziesiąt dziewięć");
      expect(slownie("190"), "sto dziewięćdziesiąt");
      expect(slownie("191"), "sto dziewięćdziesiąt jeden");
      expect(slownie("192"), "sto dziewięćdziesiąt dwa");
      expect(slownie("193"), "sto dziewięćdziesiąt trzy");
      expect(slownie("194"), "sto dziewięćdziesiąt cztery");
      expect(slownie("195"), "sto dziewięćdziesiąt pięć");
      expect(slownie("196"), "sto dziewięćdziesiąt sześć");
      expect(slownie("197"), "sto dziewięćdziesiąt siedem");
      expect(slownie("198"), "sto dziewięćdziesiąt osiem");
      expect(slownie("199"), "sto dziewięćdziesiąt dziewięć");
      expect(slownie("200"), "dwieście");
      expect(slownie("201"), "dwieście jeden");
      expect(slownie("202"), "dwieście dwa");
      expect(slownie("203"), "dwieście trzy");
      expect(slownie("204"), "dwieście cztery");
      expect(slownie("205"), "dwieście pięć");
      expect(slownie("206"), "dwieście sześć");
      expect(slownie("207"), "dwieście siedem");
      expect(slownie("208"), "dwieście osiem");
      expect(slownie("209"), "dwieście dziewięć");
      expect(slownie("210"), "dwieście dziesięć");
      expect(slownie("211"), "dwieście jedenaście");
      expect(slownie("212"), "dwieście dwanaście");
      expect(slownie("213"), "dwieście trzynaście");
      expect(slownie("214"), "dwieście czternaście");
      expect(slownie("215"), "dwieście piętnaście");
      expect(slownie("216"), "dwieście szesnaście");
      expect(slownie("217"), "dwieście siedemnaście");
      expect(slownie("218"), "dwieście osiemnaście");
      expect(slownie("219"), "dwieście dziewiętnaście");
      expect(slownie("220"), "dwieście dwadzieścia");
      expect(slownie("221"), "dwieście dwadzieścia jeden");
      expect(slownie("222"), "dwieście dwadzieścia dwa");
      expect(slownie("223"), "dwieście dwadzieścia trzy");
      expect(slownie("224"), "dwieście dwadzieścia cztery");
      expect(slownie("225"), "dwieście dwadzieścia pięć");
      expect(slownie("226"), "dwieście dwadzieścia sześć");
      expect(slownie("227"), "dwieście dwadzieścia siedem");
      expect(slownie("228"), "dwieście dwadzieścia osiem");
      expect(slownie("229"), "dwieście dwadzieścia dziewięć");
      expect(slownie("230"), "dwieście trzydzieści");
      expect(slownie("231"), "dwieście trzydzieści jeden");
      expect(slownie("232"), "dwieście trzydzieści dwa");
      expect(slownie("233"), "dwieście trzydzieści trzy");
      expect(slownie("234"), "dwieście trzydzieści cztery");
      expect(slownie("235"), "dwieście trzydzieści pięć");
      expect(slownie("236"), "dwieście trzydzieści sześć");
      expect(slownie("237"), "dwieście trzydzieści siedem");
      expect(slownie("238"), "dwieście trzydzieści osiem");
      expect(slownie("239"), "dwieście trzydzieści dziewięć");
      expect(slownie("240"), "dwieście czterdzieści");
      expect(slownie("241"), "dwieście czterdzieści jeden");
      expect(slownie("242"), "dwieście czterdzieści dwa");
      expect(slownie("243"), "dwieście czterdzieści trzy");
      expect(slownie("244"), "dwieście czterdzieści cztery");
      expect(slownie("245"), "dwieście czterdzieści pięć");
      expect(slownie("246"), "dwieście czterdzieści sześć");
      expect(slownie("247"), "dwieście czterdzieści siedem");
      expect(slownie("248"), "dwieście czterdzieści osiem");
      expect(slownie("249"), "dwieście czterdzieści dziewięć");
      expect(slownie("250"), "dwieście pięćdziesiąt");
      expect(slownie("251"), "dwieście pięćdziesiąt jeden");
      expect(slownie("252"), "dwieście pięćdziesiąt dwa");
      expect(slownie("253"), "dwieście pięćdziesiąt trzy");
      expect(slownie("254"), "dwieście pięćdziesiąt cztery");
      expect(slownie("255"), "dwieście pięćdziesiąt pięć");
      expect(slownie("256"), "dwieście pięćdziesiąt sześć");
      expect(slownie("257"), "dwieście pięćdziesiąt siedem");
      expect(slownie("258"), "dwieście pięćdziesiąt osiem");
      expect(slownie("259"), "dwieście pięćdziesiąt dziewięć");
      expect(slownie("260"), "dwieście sześćdziesiąt");
      expect(slownie("261"), "dwieście sześćdziesiąt jeden");
      expect(slownie("262"), "dwieście sześćdziesiąt dwa");
      expect(slownie("263"), "dwieście sześćdziesiąt trzy");
      expect(slownie("264"), "dwieście sześćdziesiąt cztery");
      expect(slownie("265"), "dwieście sześćdziesiąt pięć");
      expect(slownie("266"), "dwieście sześćdziesiąt sześć");
      expect(slownie("267"), "dwieście sześćdziesiąt siedem");
      expect(slownie("268"), "dwieście sześćdziesiąt osiem");
      expect(slownie("269"), "dwieście sześćdziesiąt dziewięć");
      expect(slownie("270"), "dwieście siedemdziesiąt");
      expect(slownie("271"), "dwieście siedemdziesiąt jeden");
      expect(slownie("272"), "dwieście siedemdziesiąt dwa");
      expect(slownie("273"), "dwieście siedemdziesiąt trzy");
      expect(slownie("274"), "dwieście siedemdziesiąt cztery");
      expect(slownie("275"), "dwieście siedemdziesiąt pięć");
      expect(slownie("276"), "dwieście siedemdziesiąt sześć");
      expect(slownie("277"), "dwieście siedemdziesiąt siedem");
      expect(slownie("278"), "dwieście siedemdziesiąt osiem");
      expect(slownie("279"), "dwieście siedemdziesiąt dziewięć");
      expect(slownie("280"), "dwieście osiemdziesiąt");
      expect(slownie("281"), "dwieście osiemdziesiąt jeden");
      expect(slownie("282"), "dwieście osiemdziesiąt dwa");
      expect(slownie("283"), "dwieście osiemdziesiąt trzy");
      expect(slownie("284"), "dwieście osiemdziesiąt cztery");
      expect(slownie("285"), "dwieście osiemdziesiąt pięć");
      expect(slownie("286"), "dwieście osiemdziesiąt sześć");
      expect(slownie("287"), "dwieście osiemdziesiąt siedem");
      expect(slownie("288"), "dwieście osiemdziesiąt osiem");
      expect(slownie("289"), "dwieście osiemdziesiąt dziewięć");
      expect(slownie("290"), "dwieście dziewięćdziesiąt");
      expect(slownie("291"), "dwieście dziewięćdziesiąt jeden");
      expect(slownie("292"), "dwieście dziewięćdziesiąt dwa");
      expect(slownie("293"), "dwieście dziewięćdziesiąt trzy");
      expect(slownie("294"), "dwieście dziewięćdziesiąt cztery");
      expect(slownie("295"), "dwieście dziewięćdziesiąt pięć");
      expect(slownie("296"), "dwieście dziewięćdziesiąt sześć");
      expect(slownie("297"), "dwieście dziewięćdziesiąt siedem");
      expect(slownie("298"), "dwieście dziewięćdziesiąt osiem");
      expect(slownie("299"), "dwieście dziewięćdziesiąt dziewięć");
      expect(slownie("300"), "trzysta");
      expect(slownie("301"), "trzysta jeden");
      expect(slownie("302"), "trzysta dwa");
      expect(slownie("303"), "trzysta trzy");
      expect(slownie("304"), "trzysta cztery");
      expect(slownie("305"), "trzysta pięć");
      expect(slownie("306"), "trzysta sześć");
      expect(slownie("307"), "trzysta siedem");
      expect(slownie("308"), "trzysta osiem");
      expect(slownie("309"), "trzysta dziewięć");
      expect(slownie("310"), "trzysta dziesięć");
      expect(slownie("311"), "trzysta jedenaście");
      expect(slownie("312"), "trzysta dwanaście");
      expect(slownie("313"), "trzysta trzynaście");
      expect(slownie("314"), "trzysta czternaście");
      expect(slownie("315"), "trzysta piętnaście");
      expect(slownie("316"), "trzysta szesnaście");
      expect(slownie("317"), "trzysta siedemnaście");
      expect(slownie("318"), "trzysta osiemnaście");
      expect(slownie("319"), "trzysta dziewiętnaście");
      expect(slownie("320"), "trzysta dwadzieścia");
      expect(slownie("321"), "trzysta dwadzieścia jeden");
      expect(slownie("322"), "trzysta dwadzieścia dwa");
      expect(slownie("323"), "trzysta dwadzieścia trzy");
      expect(slownie("324"), "trzysta dwadzieścia cztery");
      expect(slownie("325"), "trzysta dwadzieścia pięć");
      expect(slownie("326"), "trzysta dwadzieścia sześć");
      expect(slownie("327"), "trzysta dwadzieścia siedem");
      expect(slownie("328"), "trzysta dwadzieścia osiem");
      expect(slownie("329"), "trzysta dwadzieścia dziewięć");
      expect(slownie("330"), "trzysta trzydzieści");
      expect(slownie("331"), "trzysta trzydzieści jeden");
      expect(slownie("332"), "trzysta trzydzieści dwa");
      expect(slownie("333"), "trzysta trzydzieści trzy");
      expect(slownie("334"), "trzysta trzydzieści cztery");
      expect(slownie("335"), "trzysta trzydzieści pięć");
      expect(slownie("336"), "trzysta trzydzieści sześć");
      expect(slownie("337"), "trzysta trzydzieści siedem");
      expect(slownie("338"), "trzysta trzydzieści osiem");
      expect(slownie("339"), "trzysta trzydzieści dziewięć");
      expect(slownie("340"), "trzysta czterdzieści");
      expect(slownie("341"), "trzysta czterdzieści jeden");
      expect(slownie("342"), "trzysta czterdzieści dwa");
      expect(slownie("343"), "trzysta czterdzieści trzy");
      expect(slownie("344"), "trzysta czterdzieści cztery");
      expect(slownie("345"), "trzysta czterdzieści pięć");
      expect(slownie("346"), "trzysta czterdzieści sześć");
      expect(slownie("347"), "trzysta czterdzieści siedem");
      expect(slownie("348"), "trzysta czterdzieści osiem");
      expect(slownie("349"), "trzysta czterdzieści dziewięć");
      expect(slownie("350"), "trzysta pięćdziesiąt");
      expect(slownie("351"), "trzysta pięćdziesiąt jeden");
      expect(slownie("352"), "trzysta pięćdziesiąt dwa");
      expect(slownie("353"), "trzysta pięćdziesiąt trzy");
      expect(slownie("354"), "trzysta pięćdziesiąt cztery");
      expect(slownie("355"), "trzysta pięćdziesiąt pięć");
      expect(slownie("356"), "trzysta pięćdziesiąt sześć");
      expect(slownie("357"), "trzysta pięćdziesiąt siedem");
      expect(slownie("358"), "trzysta pięćdziesiąt osiem");
      expect(slownie("359"), "trzysta pięćdziesiąt dziewięć");
      expect(slownie("360"), "trzysta sześćdziesiąt");
      expect(slownie("361"), "trzysta sześćdziesiąt jeden");
      expect(slownie("362"), "trzysta sześćdziesiąt dwa");
      expect(slownie("363"), "trzysta sześćdziesiąt trzy");
      expect(slownie("364"), "trzysta sześćdziesiąt cztery");
      expect(slownie("365"), "trzysta sześćdziesiąt pięć");
      expect(slownie("366"), "trzysta sześćdziesiąt sześć");
      expect(slownie("367"), "trzysta sześćdziesiąt siedem");
      expect(slownie("368"), "trzysta sześćdziesiąt osiem");
      expect(slownie("369"), "trzysta sześćdziesiąt dziewięć");
      expect(slownie("370"), "trzysta siedemdziesiąt");
      expect(slownie("371"), "trzysta siedemdziesiąt jeden");
      expect(slownie("372"), "trzysta siedemdziesiąt dwa");
      expect(slownie("373"), "trzysta siedemdziesiąt trzy");
      expect(slownie("374"), "trzysta siedemdziesiąt cztery");
      expect(slownie("375"), "trzysta siedemdziesiąt pięć");
      expect(slownie("376"), "trzysta siedemdziesiąt sześć");
      expect(slownie("377"), "trzysta siedemdziesiąt siedem");
      expect(slownie("378"), "trzysta siedemdziesiąt osiem");
      expect(slownie("379"), "trzysta siedemdziesiąt dziewięć");
      expect(slownie("380"), "trzysta osiemdziesiąt");
      expect(slownie("381"), "trzysta osiemdziesiąt jeden");
      expect(slownie("382"), "trzysta osiemdziesiąt dwa");
      expect(slownie("383"), "trzysta osiemdziesiąt trzy");
      expect(slownie("384"), "trzysta osiemdziesiąt cztery");
      expect(slownie("385"), "trzysta osiemdziesiąt pięć");
      expect(slownie("386"), "trzysta osiemdziesiąt sześć");
      expect(slownie("387"), "trzysta osiemdziesiąt siedem");
      expect(slownie("388"), "trzysta osiemdziesiąt osiem");
      expect(slownie("389"), "trzysta osiemdziesiąt dziewięć");
      expect(slownie("390"), "trzysta dziewięćdziesiąt");
      expect(slownie("391"), "trzysta dziewięćdziesiąt jeden");
      expect(slownie("392"), "trzysta dziewięćdziesiąt dwa");
      expect(slownie("393"), "trzysta dziewięćdziesiąt trzy");
      expect(slownie("394"), "trzysta dziewięćdziesiąt cztery");
      expect(slownie("395"), "trzysta dziewięćdziesiąt pięć");
      expect(slownie("396"), "trzysta dziewięćdziesiąt sześć");
      expect(slownie("397"), "trzysta dziewięćdziesiąt siedem");
      expect(slownie("398"), "trzysta dziewięćdziesiąt osiem");
      expect(slownie("399"), "trzysta dziewięćdziesiąt dziewięć");
      expect(slownie("400"), "czterysta");
      expect(slownie("401"), "czterysta jeden");
      expect(slownie("402"), "czterysta dwa");
      expect(slownie("403"), "czterysta trzy");
      expect(slownie("404"), "czterysta cztery");
      expect(slownie("405"), "czterysta pięć");
      expect(slownie("406"), "czterysta sześć");
      expect(slownie("407"), "czterysta siedem");
      expect(slownie("408"), "czterysta osiem");
      expect(slownie("409"), "czterysta dziewięć");
      expect(slownie("410"), "czterysta dziesięć");
      expect(slownie("411"), "czterysta jedenaście");
      expect(slownie("412"), "czterysta dwanaście");
      expect(slownie("413"), "czterysta trzynaście");
      expect(slownie("414"), "czterysta czternaście");
      expect(slownie("415"), "czterysta piętnaście");
      expect(slownie("416"), "czterysta szesnaście");
      expect(slownie("417"), "czterysta siedemnaście");
      expect(slownie("418"), "czterysta osiemnaście");
      expect(slownie("419"), "czterysta dziewiętnaście");
      expect(slownie("420"), "czterysta dwadzieścia");
      expect(slownie("421"), "czterysta dwadzieścia jeden");
      expect(slownie("422"), "czterysta dwadzieścia dwa");
      expect(slownie("423"), "czterysta dwadzieścia trzy");
      expect(slownie("424"), "czterysta dwadzieścia cztery");
      expect(slownie("425"), "czterysta dwadzieścia pięć");
      expect(slownie("426"), "czterysta dwadzieścia sześć");
      expect(slownie("427"), "czterysta dwadzieścia siedem");
      expect(slownie("428"), "czterysta dwadzieścia osiem");
      expect(slownie("429"), "czterysta dwadzieścia dziewięć");
      expect(slownie("430"), "czterysta trzydzieści");
      expect(slownie("431"), "czterysta trzydzieści jeden");
      expect(slownie("432"), "czterysta trzydzieści dwa");
      expect(slownie("433"), "czterysta trzydzieści trzy");
      expect(slownie("434"), "czterysta trzydzieści cztery");
      expect(slownie("435"), "czterysta trzydzieści pięć");
      expect(slownie("436"), "czterysta trzydzieści sześć");
      expect(slownie("437"), "czterysta trzydzieści siedem");
      expect(slownie("438"), "czterysta trzydzieści osiem");
      expect(slownie("439"), "czterysta trzydzieści dziewięć");
      expect(slownie("440"), "czterysta czterdzieści");
      expect(slownie("441"), "czterysta czterdzieści jeden");
      expect(slownie("442"), "czterysta czterdzieści dwa");
      expect(slownie("443"), "czterysta czterdzieści trzy");
      expect(slownie("444"), "czterysta czterdzieści cztery");
      expect(slownie("445"), "czterysta czterdzieści pięć");
      expect(slownie("446"), "czterysta czterdzieści sześć");
      expect(slownie("447"), "czterysta czterdzieści siedem");
      expect(slownie("448"), "czterysta czterdzieści osiem");
      expect(slownie("449"), "czterysta czterdzieści dziewięć");
      expect(slownie("450"), "czterysta pięćdziesiąt");
      expect(slownie("451"), "czterysta pięćdziesiąt jeden");
      expect(slownie("452"), "czterysta pięćdziesiąt dwa");
      expect(slownie("453"), "czterysta pięćdziesiąt trzy");
      expect(slownie("454"), "czterysta pięćdziesiąt cztery");
      expect(slownie("455"), "czterysta pięćdziesiąt pięć");
      expect(slownie("456"), "czterysta pięćdziesiąt sześć");
      expect(slownie("457"), "czterysta pięćdziesiąt siedem");
      expect(slownie("458"), "czterysta pięćdziesiąt osiem");
      expect(slownie("459"), "czterysta pięćdziesiąt dziewięć");
      expect(slownie("460"), "czterysta sześćdziesiąt");
      expect(slownie("461"), "czterysta sześćdziesiąt jeden");
      expect(slownie("462"), "czterysta sześćdziesiąt dwa");
      expect(slownie("463"), "czterysta sześćdziesiąt trzy");
      expect(slownie("464"), "czterysta sześćdziesiąt cztery");
      expect(slownie("465"), "czterysta sześćdziesiąt pięć");
      expect(slownie("466"), "czterysta sześćdziesiąt sześć");
      expect(slownie("467"), "czterysta sześćdziesiąt siedem");
      expect(slownie("468"), "czterysta sześćdziesiąt osiem");
      expect(slownie("469"), "czterysta sześćdziesiąt dziewięć");
      expect(slownie("470"), "czterysta siedemdziesiąt");
      expect(slownie("471"), "czterysta siedemdziesiąt jeden");
      expect(slownie("472"), "czterysta siedemdziesiąt dwa");
      expect(slownie("473"), "czterysta siedemdziesiąt trzy");
      expect(slownie("474"), "czterysta siedemdziesiąt cztery");
      expect(slownie("475"), "czterysta siedemdziesiąt pięć");
      expect(slownie("476"), "czterysta siedemdziesiąt sześć");
      expect(slownie("477"), "czterysta siedemdziesiąt siedem");
      expect(slownie("478"), "czterysta siedemdziesiąt osiem");
      expect(slownie("479"), "czterysta siedemdziesiąt dziewięć");
      expect(slownie("480"), "czterysta osiemdziesiąt");
      expect(slownie("481"), "czterysta osiemdziesiąt jeden");
      expect(slownie("482"), "czterysta osiemdziesiąt dwa");
      expect(slownie("483"), "czterysta osiemdziesiąt trzy");
      expect(slownie("484"), "czterysta osiemdziesiąt cztery");
      expect(slownie("485"), "czterysta osiemdziesiąt pięć");
      expect(slownie("486"), "czterysta osiemdziesiąt sześć");
      expect(slownie("487"), "czterysta osiemdziesiąt siedem");
      expect(slownie("488"), "czterysta osiemdziesiąt osiem");
      expect(slownie("489"), "czterysta osiemdziesiąt dziewięć");
      expect(slownie("490"), "czterysta dziewięćdziesiąt");
      expect(slownie("491"), "czterysta dziewięćdziesiąt jeden");
      expect(slownie("492"), "czterysta dziewięćdziesiąt dwa");
      expect(slownie("493"), "czterysta dziewięćdziesiąt trzy");
      expect(slownie("494"), "czterysta dziewięćdziesiąt cztery");
      expect(slownie("495"), "czterysta dziewięćdziesiąt pięć");
      expect(slownie("496"), "czterysta dziewięćdziesiąt sześć");
      expect(slownie("497"), "czterysta dziewięćdziesiąt siedem");
      expect(slownie("498"), "czterysta dziewięćdziesiąt osiem");
      expect(slownie("499"), "czterysta dziewięćdziesiąt dziewięć");
      expect(slownie("500"), "pięćset");
      expect(slownie("501"), "pięćset jeden");
      expect(slownie("502"), "pięćset dwa");
      expect(slownie("503"), "pięćset trzy");
      expect(slownie("504"), "pięćset cztery");
      expect(slownie("505"), "pięćset pięć");
      expect(slownie("506"), "pięćset sześć");
      expect(slownie("507"), "pięćset siedem");
      expect(slownie("508"), "pięćset osiem");
      expect(slownie("509"), "pięćset dziewięć");
      expect(slownie("510"), "pięćset dziesięć");
      expect(slownie("511"), "pięćset jedenaście");
      expect(slownie("512"), "pięćset dwanaście");
      expect(slownie("513"), "pięćset trzynaście");
      expect(slownie("514"), "pięćset czternaście");
      expect(slownie("515"), "pięćset piętnaście");
      expect(slownie("516"), "pięćset szesnaście");
      expect(slownie("517"), "pięćset siedemnaście");
      expect(slownie("518"), "pięćset osiemnaście");
      expect(slownie("519"), "pięćset dziewiętnaście");
      expect(slownie("520"), "pięćset dwadzieścia");
      expect(slownie("521"), "pięćset dwadzieścia jeden");
      expect(slownie("522"), "pięćset dwadzieścia dwa");
      expect(slownie("523"), "pięćset dwadzieścia trzy");
      expect(slownie("524"), "pięćset dwadzieścia cztery");
      expect(slownie("525"), "pięćset dwadzieścia pięć");
      expect(slownie("526"), "pięćset dwadzieścia sześć");
      expect(slownie("527"), "pięćset dwadzieścia siedem");
      expect(slownie("528"), "pięćset dwadzieścia osiem");
      expect(slownie("529"), "pięćset dwadzieścia dziewięć");
      expect(slownie("530"), "pięćset trzydzieści");
      expect(slownie("531"), "pięćset trzydzieści jeden");
      expect(slownie("532"), "pięćset trzydzieści dwa");
      expect(slownie("533"), "pięćset trzydzieści trzy");
      expect(slownie("534"), "pięćset trzydzieści cztery");
      expect(slownie("535"), "pięćset trzydzieści pięć");
      expect(slownie("536"), "pięćset trzydzieści sześć");
      expect(slownie("537"), "pięćset trzydzieści siedem");
      expect(slownie("538"), "pięćset trzydzieści osiem");
      expect(slownie("539"), "pięćset trzydzieści dziewięć");
      expect(slownie("540"), "pięćset czterdzieści");
      expect(slownie("541"), "pięćset czterdzieści jeden");
      expect(slownie("542"), "pięćset czterdzieści dwa");
      expect(slownie("543"), "pięćset czterdzieści trzy");
      expect(slownie("544"), "pięćset czterdzieści cztery");
      expect(slownie("545"), "pięćset czterdzieści pięć");
      expect(slownie("546"), "pięćset czterdzieści sześć");
      expect(slownie("547"), "pięćset czterdzieści siedem");
      expect(slownie("548"), "pięćset czterdzieści osiem");
      expect(slownie("549"), "pięćset czterdzieści dziewięć");
      expect(slownie("550"), "pięćset pięćdziesiąt");
      expect(slownie("551"), "pięćset pięćdziesiąt jeden");
      expect(slownie("552"), "pięćset pięćdziesiąt dwa");
      expect(slownie("553"), "pięćset pięćdziesiąt trzy");
      expect(slownie("554"), "pięćset pięćdziesiąt cztery");
      expect(slownie("555"), "pięćset pięćdziesiąt pięć");
      expect(slownie("556"), "pięćset pięćdziesiąt sześć");
      expect(slownie("557"), "pięćset pięćdziesiąt siedem");
      expect(slownie("558"), "pięćset pięćdziesiąt osiem");
      expect(slownie("559"), "pięćset pięćdziesiąt dziewięć");
      expect(slownie("560"), "pięćset sześćdziesiąt");
      expect(slownie("561"), "pięćset sześćdziesiąt jeden");
      expect(slownie("562"), "pięćset sześćdziesiąt dwa");
      expect(slownie("563"), "pięćset sześćdziesiąt trzy");
      expect(slownie("564"), "pięćset sześćdziesiąt cztery");
      expect(slownie("565"), "pięćset sześćdziesiąt pięć");
      expect(slownie("566"), "pięćset sześćdziesiąt sześć");
      expect(slownie("567"), "pięćset sześćdziesiąt siedem");
      expect(slownie("568"), "pięćset sześćdziesiąt osiem");
      expect(slownie("569"), "pięćset sześćdziesiąt dziewięć");
      expect(slownie("570"), "pięćset siedemdziesiąt");
      expect(slownie("571"), "pięćset siedemdziesiąt jeden");
      expect(slownie("572"), "pięćset siedemdziesiąt dwa");
      expect(slownie("573"), "pięćset siedemdziesiąt trzy");
      expect(slownie("574"), "pięćset siedemdziesiąt cztery");
      expect(slownie("575"), "pięćset siedemdziesiąt pięć");
      expect(slownie("576"), "pięćset siedemdziesiąt sześć");
      expect(slownie("577"), "pięćset siedemdziesiąt siedem");
      expect(slownie("578"), "pięćset siedemdziesiąt osiem");
      expect(slownie("579"), "pięćset siedemdziesiąt dziewięć");
      expect(slownie("580"), "pięćset osiemdziesiąt");
      expect(slownie("581"), "pięćset osiemdziesiąt jeden");
      expect(slownie("582"), "pięćset osiemdziesiąt dwa");
      expect(slownie("583"), "pięćset osiemdziesiąt trzy");
      expect(slownie("584"), "pięćset osiemdziesiąt cztery");
      expect(slownie("585"), "pięćset osiemdziesiąt pięć");
      expect(slownie("586"), "pięćset osiemdziesiąt sześć");
      expect(slownie("587"), "pięćset osiemdziesiąt siedem");
      expect(slownie("588"), "pięćset osiemdziesiąt osiem");
      expect(slownie("589"), "pięćset osiemdziesiąt dziewięć");
      expect(slownie("590"), "pięćset dziewięćdziesiąt");
      expect(slownie("591"), "pięćset dziewięćdziesiąt jeden");
      expect(slownie("592"), "pięćset dziewięćdziesiąt dwa");
      expect(slownie("593"), "pięćset dziewięćdziesiąt trzy");
      expect(slownie("594"), "pięćset dziewięćdziesiąt cztery");
      expect(slownie("595"), "pięćset dziewięćdziesiąt pięć");
      expect(slownie("596"), "pięćset dziewięćdziesiąt sześć");
      expect(slownie("597"), "pięćset dziewięćdziesiąt siedem");
      expect(slownie("598"), "pięćset dziewięćdziesiąt osiem");
      expect(slownie("599"), "pięćset dziewięćdziesiąt dziewięć");
      expect(slownie("600"), "sześćset");
      expect(slownie("601"), "sześćset jeden");
      expect(slownie("602"), "sześćset dwa");
      expect(slownie("603"), "sześćset trzy");
      expect(slownie("604"), "sześćset cztery");
      expect(slownie("605"), "sześćset pięć");
      expect(slownie("606"), "sześćset sześć");
      expect(slownie("607"), "sześćset siedem");
      expect(slownie("608"), "sześćset osiem");
      expect(slownie("609"), "sześćset dziewięć");
      expect(slownie("610"), "sześćset dziesięć");
      expect(slownie("611"), "sześćset jedenaście");
      expect(slownie("612"), "sześćset dwanaście");
      expect(slownie("613"), "sześćset trzynaście");
      expect(slownie("614"), "sześćset czternaście");
      expect(slownie("615"), "sześćset piętnaście");
      expect(slownie("616"), "sześćset szesnaście");
      expect(slownie("617"), "sześćset siedemnaście");
      expect(slownie("618"), "sześćset osiemnaście");
      expect(slownie("619"), "sześćset dziewiętnaście");
      expect(slownie("620"), "sześćset dwadzieścia");
      expect(slownie("621"), "sześćset dwadzieścia jeden");
      expect(slownie("622"), "sześćset dwadzieścia dwa");
      expect(slownie("623"), "sześćset dwadzieścia trzy");
      expect(slownie("624"), "sześćset dwadzieścia cztery");
      expect(slownie("625"), "sześćset dwadzieścia pięć");
      expect(slownie("626"), "sześćset dwadzieścia sześć");
      expect(slownie("627"), "sześćset dwadzieścia siedem");
      expect(slownie("628"), "sześćset dwadzieścia osiem");
      expect(slownie("629"), "sześćset dwadzieścia dziewięć");
      expect(slownie("630"), "sześćset trzydzieści");
      expect(slownie("631"), "sześćset trzydzieści jeden");
      expect(slownie("632"), "sześćset trzydzieści dwa");
      expect(slownie("633"), "sześćset trzydzieści trzy");
      expect(slownie("634"), "sześćset trzydzieści cztery");
      expect(slownie("635"), "sześćset trzydzieści pięć");
      expect(slownie("636"), "sześćset trzydzieści sześć");
      expect(slownie("637"), "sześćset trzydzieści siedem");
      expect(slownie("638"), "sześćset trzydzieści osiem");
      expect(slownie("639"), "sześćset trzydzieści dziewięć");
      expect(slownie("640"), "sześćset czterdzieści");
      expect(slownie("641"), "sześćset czterdzieści jeden");
      expect(slownie("642"), "sześćset czterdzieści dwa");
      expect(slownie("643"), "sześćset czterdzieści trzy");
      expect(slownie("644"), "sześćset czterdzieści cztery");
      expect(slownie("645"), "sześćset czterdzieści pięć");
      expect(slownie("646"), "sześćset czterdzieści sześć");
      expect(slownie("647"), "sześćset czterdzieści siedem");
      expect(slownie("648"), "sześćset czterdzieści osiem");
      expect(slownie("649"), "sześćset czterdzieści dziewięć");
      expect(slownie("650"), "sześćset pięćdziesiąt");
      expect(slownie("651"), "sześćset pięćdziesiąt jeden");
      expect(slownie("652"), "sześćset pięćdziesiąt dwa");
      expect(slownie("653"), "sześćset pięćdziesiąt trzy");
      expect(slownie("654"), "sześćset pięćdziesiąt cztery");
      expect(slownie("655"), "sześćset pięćdziesiąt pięć");
      expect(slownie("656"), "sześćset pięćdziesiąt sześć");
      expect(slownie("657"), "sześćset pięćdziesiąt siedem");
      expect(slownie("658"), "sześćset pięćdziesiąt osiem");
      expect(slownie("659"), "sześćset pięćdziesiąt dziewięć");
      expect(slownie("660"), "sześćset sześćdziesiąt");
      expect(slownie("661"), "sześćset sześćdziesiąt jeden");
      expect(slownie("662"), "sześćset sześćdziesiąt dwa");
      expect(slownie("663"), "sześćset sześćdziesiąt trzy");
      expect(slownie("664"), "sześćset sześćdziesiąt cztery");
      expect(slownie("665"), "sześćset sześćdziesiąt pięć");
      expect(slownie("666"), "sześćset sześćdziesiąt sześć");
      expect(slownie("667"), "sześćset sześćdziesiąt siedem");
      expect(slownie("668"), "sześćset sześćdziesiąt osiem");
      expect(slownie("669"), "sześćset sześćdziesiąt dziewięć");
      expect(slownie("670"), "sześćset siedemdziesiąt");
      expect(slownie("671"), "sześćset siedemdziesiąt jeden");
      expect(slownie("672"), "sześćset siedemdziesiąt dwa");
      expect(slownie("673"), "sześćset siedemdziesiąt trzy");
      expect(slownie("674"), "sześćset siedemdziesiąt cztery");
      expect(slownie("675"), "sześćset siedemdziesiąt pięć");
      expect(slownie("676"), "sześćset siedemdziesiąt sześć");
      expect(slownie("677"), "sześćset siedemdziesiąt siedem");
      expect(slownie("678"), "sześćset siedemdziesiąt osiem");
      expect(slownie("679"), "sześćset siedemdziesiąt dziewięć");
      expect(slownie("680"), "sześćset osiemdziesiąt");
      expect(slownie("681"), "sześćset osiemdziesiąt jeden");
      expect(slownie("682"), "sześćset osiemdziesiąt dwa");
      expect(slownie("683"), "sześćset osiemdziesiąt trzy");
      expect(slownie("684"), "sześćset osiemdziesiąt cztery");
      expect(slownie("685"), "sześćset osiemdziesiąt pięć");
      expect(slownie("686"), "sześćset osiemdziesiąt sześć");
      expect(slownie("687"), "sześćset osiemdziesiąt siedem");
      expect(slownie("688"), "sześćset osiemdziesiąt osiem");
      expect(slownie("689"), "sześćset osiemdziesiąt dziewięć");
      expect(slownie("690"), "sześćset dziewięćdziesiąt");
      expect(slownie("691"), "sześćset dziewięćdziesiąt jeden");
      expect(slownie("692"), "sześćset dziewięćdziesiąt dwa");
      expect(slownie("693"), "sześćset dziewięćdziesiąt trzy");
      expect(slownie("694"), "sześćset dziewięćdziesiąt cztery");
      expect(slownie("695"), "sześćset dziewięćdziesiąt pięć");
      expect(slownie("696"), "sześćset dziewięćdziesiąt sześć");
      expect(slownie("697"), "sześćset dziewięćdziesiąt siedem");
      expect(slownie("698"), "sześćset dziewięćdziesiąt osiem");
      expect(slownie("699"), "sześćset dziewięćdziesiąt dziewięć");
      expect(slownie("700"), "siedemset");
      expect(slownie("701"), "siedemset jeden");
      expect(slownie("702"), "siedemset dwa");
      expect(slownie("703"), "siedemset trzy");
      expect(slownie("704"), "siedemset cztery");
      expect(slownie("705"), "siedemset pięć");
      expect(slownie("706"), "siedemset sześć");
      expect(slownie("707"), "siedemset siedem");
      expect(slownie("708"), "siedemset osiem");
      expect(slownie("709"), "siedemset dziewięć");
      expect(slownie("710"), "siedemset dziesięć");
      expect(slownie("711"), "siedemset jedenaście");
      expect(slownie("712"), "siedemset dwanaście");
      expect(slownie("713"), "siedemset trzynaście");
      expect(slownie("714"), "siedemset czternaście");
      expect(slownie("715"), "siedemset piętnaście");
      expect(slownie("716"), "siedemset szesnaście");
      expect(slownie("717"), "siedemset siedemnaście");
      expect(slownie("718"), "siedemset osiemnaście");
      expect(slownie("719"), "siedemset dziewiętnaście");
      expect(slownie("720"), "siedemset dwadzieścia");
      expect(slownie("721"), "siedemset dwadzieścia jeden");
      expect(slownie("722"), "siedemset dwadzieścia dwa");
      expect(slownie("723"), "siedemset dwadzieścia trzy");
      expect(slownie("724"), "siedemset dwadzieścia cztery");
      expect(slownie("725"), "siedemset dwadzieścia pięć");
      expect(slownie("726"), "siedemset dwadzieścia sześć");
      expect(slownie("727"), "siedemset dwadzieścia siedem");
      expect(slownie("728"), "siedemset dwadzieścia osiem");
      expect(slownie("729"), "siedemset dwadzieścia dziewięć");
      expect(slownie("730"), "siedemset trzydzieści");
      expect(slownie("731"), "siedemset trzydzieści jeden");
      expect(slownie("732"), "siedemset trzydzieści dwa");
      expect(slownie("733"), "siedemset trzydzieści trzy");
      expect(slownie("734"), "siedemset trzydzieści cztery");
      expect(slownie("735"), "siedemset trzydzieści pięć");
      expect(slownie("736"), "siedemset trzydzieści sześć");
      expect(slownie("737"), "siedemset trzydzieści siedem");
      expect(slownie("738"), "siedemset trzydzieści osiem");
      expect(slownie("739"), "siedemset trzydzieści dziewięć");
      expect(slownie("740"), "siedemset czterdzieści");
      expect(slownie("741"), "siedemset czterdzieści jeden");
      expect(slownie("742"), "siedemset czterdzieści dwa");
      expect(slownie("743"), "siedemset czterdzieści trzy");
      expect(slownie("744"), "siedemset czterdzieści cztery");
      expect(slownie("745"), "siedemset czterdzieści pięć");
      expect(slownie("746"), "siedemset czterdzieści sześć");
      expect(slownie("747"), "siedemset czterdzieści siedem");
      expect(slownie("748"), "siedemset czterdzieści osiem");
      expect(slownie("749"), "siedemset czterdzieści dziewięć");
      expect(slownie("750"), "siedemset pięćdziesiąt");
      expect(slownie("751"), "siedemset pięćdziesiąt jeden");
      expect(slownie("752"), "siedemset pięćdziesiąt dwa");
      expect(slownie("753"), "siedemset pięćdziesiąt trzy");
      expect(slownie("754"), "siedemset pięćdziesiąt cztery");
      expect(slownie("755"), "siedemset pięćdziesiąt pięć");
      expect(slownie("756"), "siedemset pięćdziesiąt sześć");
      expect(slownie("757"), "siedemset pięćdziesiąt siedem");
      expect(slownie("758"), "siedemset pięćdziesiąt osiem");
      expect(slownie("759"), "siedemset pięćdziesiąt dziewięć");
      expect(slownie("760"), "siedemset sześćdziesiąt");
      expect(slownie("761"), "siedemset sześćdziesiąt jeden");
      expect(slownie("762"), "siedemset sześćdziesiąt dwa");
      expect(slownie("763"), "siedemset sześćdziesiąt trzy");
      expect(slownie("764"), "siedemset sześćdziesiąt cztery");
      expect(slownie("765"), "siedemset sześćdziesiąt pięć");
      expect(slownie("766"), "siedemset sześćdziesiąt sześć");
      expect(slownie("767"), "siedemset sześćdziesiąt siedem");
      expect(slownie("768"), "siedemset sześćdziesiąt osiem");
      expect(slownie("769"), "siedemset sześćdziesiąt dziewięć");
      expect(slownie("770"), "siedemset siedemdziesiąt");
      expect(slownie("771"), "siedemset siedemdziesiąt jeden");
      expect(slownie("772"), "siedemset siedemdziesiąt dwa");
      expect(slownie("773"), "siedemset siedemdziesiąt trzy");
      expect(slownie("774"), "siedemset siedemdziesiąt cztery");
      expect(slownie("775"), "siedemset siedemdziesiąt pięć");
      expect(slownie("776"), "siedemset siedemdziesiąt sześć");
      expect(slownie("777"), "siedemset siedemdziesiąt siedem");
      expect(slownie("778"), "siedemset siedemdziesiąt osiem");
      expect(slownie("779"), "siedemset siedemdziesiąt dziewięć");
      expect(slownie("780"), "siedemset osiemdziesiąt");
      expect(slownie("781"), "siedemset osiemdziesiąt jeden");
      expect(slownie("782"), "siedemset osiemdziesiąt dwa");
      expect(slownie("783"), "siedemset osiemdziesiąt trzy");
      expect(slownie("784"), "siedemset osiemdziesiąt cztery");
      expect(slownie("785"), "siedemset osiemdziesiąt pięć");
      expect(slownie("786"), "siedemset osiemdziesiąt sześć");
      expect(slownie("787"), "siedemset osiemdziesiąt siedem");
      expect(slownie("788"), "siedemset osiemdziesiąt osiem");
      expect(slownie("789"), "siedemset osiemdziesiąt dziewięć");
      expect(slownie("790"), "siedemset dziewięćdziesiąt");
      expect(slownie("791"), "siedemset dziewięćdziesiąt jeden");
      expect(slownie("792"), "siedemset dziewięćdziesiąt dwa");
      expect(slownie("793"), "siedemset dziewięćdziesiąt trzy");
      expect(slownie("794"), "siedemset dziewięćdziesiąt cztery");
      expect(slownie("795"), "siedemset dziewięćdziesiąt pięć");
      expect(slownie("796"), "siedemset dziewięćdziesiąt sześć");
      expect(slownie("797"), "siedemset dziewięćdziesiąt siedem");
      expect(slownie("798"), "siedemset dziewięćdziesiąt osiem");
      expect(slownie("799"), "siedemset dziewięćdziesiąt dziewięć");
      expect(slownie("800"), "osiemset");
      expect(slownie("801"), "osiemset jeden");
      expect(slownie("802"), "osiemset dwa");
      expect(slownie("803"), "osiemset trzy");
      expect(slownie("804"), "osiemset cztery");
      expect(slownie("805"), "osiemset pięć");
      expect(slownie("806"), "osiemset sześć");
      expect(slownie("807"), "osiemset siedem");
      expect(slownie("808"), "osiemset osiem");
      expect(slownie("809"), "osiemset dziewięć");
      expect(slownie("810"), "osiemset dziesięć");
      expect(slownie("811"), "osiemset jedenaście");
      expect(slownie("812"), "osiemset dwanaście");
      expect(slownie("813"), "osiemset trzynaście");
      expect(slownie("814"), "osiemset czternaście");
      expect(slownie("815"), "osiemset piętnaście");
      expect(slownie("816"), "osiemset szesnaście");
      expect(slownie("817"), "osiemset siedemnaście");
      expect(slownie("818"), "osiemset osiemnaście");
      expect(slownie("819"), "osiemset dziewiętnaście");
      expect(slownie("820"), "osiemset dwadzieścia");
      expect(slownie("821"), "osiemset dwadzieścia jeden");
      expect(slownie("822"), "osiemset dwadzieścia dwa");
      expect(slownie("823"), "osiemset dwadzieścia trzy");
      expect(slownie("824"), "osiemset dwadzieścia cztery");
      expect(slownie("825"), "osiemset dwadzieścia pięć");
      expect(slownie("826"), "osiemset dwadzieścia sześć");
      expect(slownie("827"), "osiemset dwadzieścia siedem");
      expect(slownie("828"), "osiemset dwadzieścia osiem");
      expect(slownie("829"), "osiemset dwadzieścia dziewięć");
      expect(slownie("830"), "osiemset trzydzieści");
      expect(slownie("831"), "osiemset trzydzieści jeden");
      expect(slownie("832"), "osiemset trzydzieści dwa");
      expect(slownie("833"), "osiemset trzydzieści trzy");
      expect(slownie("834"), "osiemset trzydzieści cztery");
      expect(slownie("835"), "osiemset trzydzieści pięć");
      expect(slownie("836"), "osiemset trzydzieści sześć");
      expect(slownie("837"), "osiemset trzydzieści siedem");
      expect(slownie("838"), "osiemset trzydzieści osiem");
      expect(slownie("839"), "osiemset trzydzieści dziewięć");
      expect(slownie("840"), "osiemset czterdzieści");
      expect(slownie("841"), "osiemset czterdzieści jeden");
      expect(slownie("842"), "osiemset czterdzieści dwa");
      expect(slownie("843"), "osiemset czterdzieści trzy");
      expect(slownie("844"), "osiemset czterdzieści cztery");
      expect(slownie("845"), "osiemset czterdzieści pięć");
      expect(slownie("846"), "osiemset czterdzieści sześć");
      expect(slownie("847"), "osiemset czterdzieści siedem");
      expect(slownie("848"), "osiemset czterdzieści osiem");
      expect(slownie("849"), "osiemset czterdzieści dziewięć");
      expect(slownie("850"), "osiemset pięćdziesiąt");
      expect(slownie("851"), "osiemset pięćdziesiąt jeden");
      expect(slownie("852"), "osiemset pięćdziesiąt dwa");
      expect(slownie("853"), "osiemset pięćdziesiąt trzy");
      expect(slownie("854"), "osiemset pięćdziesiąt cztery");
      expect(slownie("855"), "osiemset pięćdziesiąt pięć");
      expect(slownie("856"), "osiemset pięćdziesiąt sześć");
      expect(slownie("857"), "osiemset pięćdziesiąt siedem");
      expect(slownie("858"), "osiemset pięćdziesiąt osiem");
      expect(slownie("859"), "osiemset pięćdziesiąt dziewięć");
      expect(slownie("860"), "osiemset sześćdziesiąt");
      expect(slownie("861"), "osiemset sześćdziesiąt jeden");
      expect(slownie("862"), "osiemset sześćdziesiąt dwa");
      expect(slownie("863"), "osiemset sześćdziesiąt trzy");
      expect(slownie("864"), "osiemset sześćdziesiąt cztery");
      expect(slownie("865"), "osiemset sześćdziesiąt pięć");
      expect(slownie("866"), "osiemset sześćdziesiąt sześć");
      expect(slownie("867"), "osiemset sześćdziesiąt siedem");
      expect(slownie("868"), "osiemset sześćdziesiąt osiem");
      expect(slownie("869"), "osiemset sześćdziesiąt dziewięć");
      expect(slownie("870"), "osiemset siedemdziesiąt");
      expect(slownie("871"), "osiemset siedemdziesiąt jeden");
      expect(slownie("872"), "osiemset siedemdziesiąt dwa");
      expect(slownie("873"), "osiemset siedemdziesiąt trzy");
      expect(slownie("874"), "osiemset siedemdziesiąt cztery");
      expect(slownie("875"), "osiemset siedemdziesiąt pięć");
      expect(slownie("876"), "osiemset siedemdziesiąt sześć");
      expect(slownie("877"), "osiemset siedemdziesiąt siedem");
      expect(slownie("878"), "osiemset siedemdziesiąt osiem");
      expect(slownie("879"), "osiemset siedemdziesiąt dziewięć");
      expect(slownie("880"), "osiemset osiemdziesiąt");
      expect(slownie("881"), "osiemset osiemdziesiąt jeden");
      expect(slownie("882"), "osiemset osiemdziesiąt dwa");
      expect(slownie("883"), "osiemset osiemdziesiąt trzy");
      expect(slownie("884"), "osiemset osiemdziesiąt cztery");
      expect(slownie("885"), "osiemset osiemdziesiąt pięć");
      expect(slownie("886"), "osiemset osiemdziesiąt sześć");
      expect(slownie("887"), "osiemset osiemdziesiąt siedem");
      expect(slownie("888"), "osiemset osiemdziesiąt osiem");
      expect(slownie("889"), "osiemset osiemdziesiąt dziewięć");
      expect(slownie("890"), "osiemset dziewięćdziesiąt");
      expect(slownie("891"), "osiemset dziewięćdziesiąt jeden");
      expect(slownie("892"), "osiemset dziewięćdziesiąt dwa");
      expect(slownie("893"), "osiemset dziewięćdziesiąt trzy");
      expect(slownie("894"), "osiemset dziewięćdziesiąt cztery");
      expect(slownie("895"), "osiemset dziewięćdziesiąt pięć");
      expect(slownie("896"), "osiemset dziewięćdziesiąt sześć");
      expect(slownie("897"), "osiemset dziewięćdziesiąt siedem");
      expect(slownie("898"), "osiemset dziewięćdziesiąt osiem");
      expect(slownie("899"), "osiemset dziewięćdziesiąt dziewięć");
      expect(slownie("900"), "dziewięćset");
      expect(slownie("901"), "dziewięćset jeden");
      expect(slownie("902"), "dziewięćset dwa");
      expect(slownie("903"), "dziewięćset trzy");
      expect(slownie("904"), "dziewięćset cztery");
      expect(slownie("905"), "dziewięćset pięć");
      expect(slownie("906"), "dziewięćset sześć");
      expect(slownie("907"), "dziewięćset siedem");
      expect(slownie("908"), "dziewięćset osiem");
      expect(slownie("909"), "dziewięćset dziewięć");
      expect(slownie("910"), "dziewięćset dziesięć");
      expect(slownie("911"), "dziewięćset jedenaście");
      expect(slownie("912"), "dziewięćset dwanaście");
      expect(slownie("913"), "dziewięćset trzynaście");
      expect(slownie("914"), "dziewięćset czternaście");
      expect(slownie("915"), "dziewięćset piętnaście");
      expect(slownie("916"), "dziewięćset szesnaście");
      expect(slownie("917"), "dziewięćset siedemnaście");
      expect(slownie("918"), "dziewięćset osiemnaście");
      expect(slownie("919"), "dziewięćset dziewiętnaście");
      expect(slownie("920"), "dziewięćset dwadzieścia");
      expect(slownie("921"), "dziewięćset dwadzieścia jeden");
      expect(slownie("922"), "dziewięćset dwadzieścia dwa");
      expect(slownie("923"), "dziewięćset dwadzieścia trzy");
      expect(slownie("924"), "dziewięćset dwadzieścia cztery");
      expect(slownie("925"), "dziewięćset dwadzieścia pięć");
      expect(slownie("926"), "dziewięćset dwadzieścia sześć");
      expect(slownie("927"), "dziewięćset dwadzieścia siedem");
      expect(slownie("928"), "dziewięćset dwadzieścia osiem");
      expect(slownie("929"), "dziewięćset dwadzieścia dziewięć");
      expect(slownie("930"), "dziewięćset trzydzieści");
      expect(slownie("931"), "dziewięćset trzydzieści jeden");
      expect(slownie("932"), "dziewięćset trzydzieści dwa");
      expect(slownie("933"), "dziewięćset trzydzieści trzy");
      expect(slownie("934"), "dziewięćset trzydzieści cztery");
      expect(slownie("935"), "dziewięćset trzydzieści pięć");
      expect(slownie("936"), "dziewięćset trzydzieści sześć");
      expect(slownie("937"), "dziewięćset trzydzieści siedem");
      expect(slownie("938"), "dziewięćset trzydzieści osiem");
      expect(slownie("939"), "dziewięćset trzydzieści dziewięć");
      expect(slownie("940"), "dziewięćset czterdzieści");
      expect(slownie("941"), "dziewięćset czterdzieści jeden");
      expect(slownie("942"), "dziewięćset czterdzieści dwa");
      expect(slownie("943"), "dziewięćset czterdzieści trzy");
      expect(slownie("944"), "dziewięćset czterdzieści cztery");
      expect(slownie("945"), "dziewięćset czterdzieści pięć");
      expect(slownie("946"), "dziewięćset czterdzieści sześć");
      expect(slownie("947"), "dziewięćset czterdzieści siedem");
      expect(slownie("948"), "dziewięćset czterdzieści osiem");
      expect(slownie("949"), "dziewięćset czterdzieści dziewięć");
      expect(slownie("950"), "dziewięćset pięćdziesiąt");
      expect(slownie("951"), "dziewięćset pięćdziesiąt jeden");
      expect(slownie("952"), "dziewięćset pięćdziesiąt dwa");
      expect(slownie("953"), "dziewięćset pięćdziesiąt trzy");
      expect(slownie("954"), "dziewięćset pięćdziesiąt cztery");
      expect(slownie("955"), "dziewięćset pięćdziesiąt pięć");
      expect(slownie("956"), "dziewięćset pięćdziesiąt sześć");
      expect(slownie("957"), "dziewięćset pięćdziesiąt siedem");
      expect(slownie("958"), "dziewięćset pięćdziesiąt osiem");
      expect(slownie("959"), "dziewięćset pięćdziesiąt dziewięć");
      expect(slownie("960"), "dziewięćset sześćdziesiąt");
      expect(slownie("961"), "dziewięćset sześćdziesiąt jeden");
      expect(slownie("962"), "dziewięćset sześćdziesiąt dwa");
      expect(slownie("963"), "dziewięćset sześćdziesiąt trzy");
      expect(slownie("964"), "dziewięćset sześćdziesiąt cztery");
      expect(slownie("965"), "dziewięćset sześćdziesiąt pięć");
      expect(slownie("966"), "dziewięćset sześćdziesiąt sześć");
      expect(slownie("967"), "dziewięćset sześćdziesiąt siedem");
      expect(slownie("968"), "dziewięćset sześćdziesiąt osiem");
      expect(slownie("969"), "dziewięćset sześćdziesiąt dziewięć");
      expect(slownie("970"), "dziewięćset siedemdziesiąt");
      expect(slownie("971"), "dziewięćset siedemdziesiąt jeden");
      expect(slownie("972"), "dziewięćset siedemdziesiąt dwa");
      expect(slownie("973"), "dziewięćset siedemdziesiąt trzy");
      expect(slownie("974"), "dziewięćset siedemdziesiąt cztery");
      expect(slownie("975"), "dziewięćset siedemdziesiąt pięć");
      expect(slownie("976"), "dziewięćset siedemdziesiąt sześć");
      expect(slownie("977"), "dziewięćset siedemdziesiąt siedem");
      expect(slownie("978"), "dziewięćset siedemdziesiąt osiem");
      expect(slownie("979"), "dziewięćset siedemdziesiąt dziewięć");
      expect(slownie("980"), "dziewięćset osiemdziesiąt");
      expect(slownie("981"), "dziewięćset osiemdziesiąt jeden");
      expect(slownie("982"), "dziewięćset osiemdziesiąt dwa");
      expect(slownie("983"), "dziewięćset osiemdziesiąt trzy");
      expect(slownie("984"), "dziewięćset osiemdziesiąt cztery");
      expect(slownie("985"), "dziewięćset osiemdziesiąt pięć");
      expect(slownie("986"), "dziewięćset osiemdziesiąt sześć");
      expect(slownie("987"), "dziewięćset osiemdziesiąt siedem");
      expect(slownie("988"), "dziewięćset osiemdziesiąt osiem");
      expect(slownie("989"), "dziewięćset osiemdziesiąt dziewięć");
      expect(slownie("990"), "dziewięćset dziewięćdziesiąt");
      expect(slownie("991"), "dziewięćset dziewięćdziesiąt jeden");
      expect(slownie("992"), "dziewięćset dziewięćdziesiąt dwa");
      expect(slownie("993"), "dziewięćset dziewięćdziesiąt trzy");
      expect(slownie("994"), "dziewięćset dziewięćdziesiąt cztery");
      expect(slownie("995"), "dziewięćset dziewięćdziesiąt pięć");
      expect(slownie("996"), "dziewięćset dziewięćdziesiąt sześć");
      expect(slownie("997"), "dziewięćset dziewięćdziesiąt siedem");
      expect(slownie("998"), "dziewięćset dziewięćdziesiąt osiem");
      expect(slownie("999"), "dziewięćset dziewięćdziesiąt dziewięć");
      expect(slownie("1000"), "tysiąc");
    });
    
    
    
  });
}